name = "SBT"
uuid = "a230e6b4-601e-4928-8f3a-78619b4f94b1"
version = "0.1.0"
authors = ["Austin Zadoks <austin.zadoks@protonmail.com>"]

[deps]
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Bessels = "0.2"
FFTW = "1.10"
LinearAlgebra = "1"
SpecialFunctions = "2.7"
